CONFIGURATION IoAddresses
    VAR_GLOBAL
        ET200SP_1_AI1_InputAddress AT %IL28: LWORD;
        ET200SP_1_DI1_InputAddress AT %IB0: BYTE;
        ET200SP_1_DQ1_OutputAddress AT %QB2: BYTE;
        ET200SP_2_AI1_InputAddress_0 AT %IB19: BYTE;
        ET200SP_2_AI1_InputAddress_1 AT %IB20: BYTE;
        ET200SP_2_AI1_InputAddress_2 AT %IB21: BYTE;
        ET200SP_2_AI1_InputAddress_3 AT %IB22: BYTE;
        ET200SP_2_AI1_InputAddress_4 AT %IB23: BYTE;
        ET200SP_2_AI1_InputAddress_5 AT %IB24: BYTE;
        ET200SP_2_AI1_InputAddress_6 AT %IB25: BYTE;
        ET200SP_2_AI1_InputAddress_7 AT %IB26: BYTE;
        ET200SP_2_AI1_InputAddress_8 AT %IB27: BYTE;
        ET200SP_2_AI2_InputAddress_0 AT %IB10: BYTE;
        ET200SP_2_AI2_InputAddress_1 AT %IB11: BYTE;
        ET200SP_2_AI2_InputAddress_2 AT %IB12: BYTE;
        ET200SP_2_AI2_InputAddress_3 AT %IB13: BYTE;
        ET200SP_2_AI2_InputAddress_4 AT %IB14: BYTE;
        ET200SP_2_AI2_InputAddress_5 AT %IB15: BYTE;
        ET200SP_2_AI2_InputAddress_6 AT %IB16: BYTE;
        ET200SP_2_AI2_InputAddress_7 AT %IB17: BYTE;
        ET200SP_2_AI2_InputAddress_8 AT %IB18: BYTE;
        ET200SP_2_AI3_InputAddress_0 AT %IB1: BYTE;
        ET200SP_2_AI3_InputAddress_1 AT %IB2: BYTE;
        ET200SP_2_AI3_InputAddress_2 AT %IB3: BYTE;
        ET200SP_2_AI3_InputAddress_3 AT %IB4: BYTE;
        ET200SP_2_AI3_InputAddress_4 AT %IB5: BYTE;
        ET200SP_2_AI3_InputAddress_5 AT %IB6: BYTE;
        ET200SP_2_AI3_InputAddress_6 AT %IB7: BYTE;
        ET200SP_2_AI3_InputAddress_7 AT %IB8: BYTE;
        ET200SP_2_AI3_InputAddress_8 AT %IB9: BYTE;

    END_VAR
END_CONFIGURATION
